resolver: lts-8.4
packages:
- location: .
- location: hxt
- location: conduit
extra-deps:
- Stream-0.4.7.2
- arrows-0.4.4.1
- lazysmallcheck-0.6
ghc-options:
  invertible: -Wall -Werror -Wno-orphans
  invertible-hxt: -Wall -Werror
  invertible-conduit: -Wall -Werror
